# Generated by Django 6.1.2 on 2026-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0002_syncjob_syncattempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="channel",
            field=models.CharField(
                choices=[
                    ("SHOPIFY", "Shopify"),
                    ("WOOCOMMERCE", "Woocommerce"),
                    ("DEMO", "Demo"),
                ],
                max_length=20,
            ),
        ),
    ]
