# Generated by Django 6.1.2 on 2026-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0003_alter_channelconnection_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelconnection",
            name="auto_process",
            field=models.CharField(
                choices=[
                    ("MANUAL", "MANUAL"),
                    ("CONFIRM", "CONFIRM"),
                    ("PACK", "PACK"),
                ],
                default="MANUAL",
                max_length=10,
            ),
        ),
    ]
